server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
  data:
    jpa:
      repositories:
        bootstrap-mode: default

